### ISSUE TITLE
Minor Formatting for Upcoming Tournaments

### ISSUE THREAD

**Issue by chinmay314** [wolfe3d/sodata#25]
I noticed that there's a disproportionately large break between each event as a result of the nested unordered lists we have for partners. I copied the html with inspect element and ran that file, only to see no such awkward spacing.

Is there a quick way to reduce or remove the spacing with CSS, considering that's probably the reason for the spacing?

![image](https://user-images.githubusercontent.com/64321319/138541803-0e54d358-173a-4620-a0d4-0ef0bf00cd5f.png)
![image](https://user-images.githubusercontent.com/64321319/138541805-c8933117-0900-4c37-b40e-6450eb637664.png)

**Comment by wolfe3d** [comment]
If this is still an issue, show me in person, so I can inspect the element and see if it is an html or css issue.
