### ISSUE TITLE
Events, Time Blocks Issue

### ISSUE THREAD

**Issue by chinmay314** [wolfe3d/sodata#26]
Similar to how the site currently allows us to remove students from a team when they still have events, the site also allows us to remove events from time blocks without removing the teams that were assigned to them. Currently it needs us to uncheck the teams first, then remove them from the time block. I will see if I can implement a warning system for both ASAP.

I encountered this error when fixing the time blocks for UGA.

**Comment by wolfe3d** [comment]
I made some edits to the teamedit page to add to the warning system.  I changed how you were return values.  Use the exit() function to end a php script with an error.  However, I have not added a warning for removing a student from a team when they still have events.  I figured you could do this, so I left a todo marker for you as to where to add this.

**Comment by wolfe3d** [comment]
I believe I added sufficient blocking of events that might deteriorate the database.  You can no longer remove a possible timeblock unless it is not assigned.  You can no longer remove an event unless there is not a timeblock, and no students are assigned to it.
