### ISSUE TITLE
Flight event named as Helicopter under Events tab

### ISSUE THREAD

**Issue by RyanTan8** [wolfe3d/sodata#39]
Flight is named as "Helicopter" under the events tab

**Comment by wolfe3d** [comment]
This is a fix that you can do.  Go to events and rename Helicopter.

**Comment by wolfe3d** [comment]
On second thought, I will add Flight and we will need to modify changes elsewhere.  I will do this.

**Comment by wolfe3d** [comment]
Bug in adding events...I must track this.

**Comment by wolfe3d** [comment]
I believe I have finished changing all references from helicopter to flight.  I have left helicopter as an event in the database because it has been a trial event.
