### ISSUE TITLE
Incorrect number of students assigned to event

### ISSUE THREAD

**Issue by RyanTan8** [wolfe3d/sodata#40]

**Comment by RyanTan8** [comment]
"Get emails" button under the events tab shows the incorrect number of students assigned to the event

**Comment by wolfe3d** [comment]
I have made it so that the event emails page show each nonCompetition tournament (Fall assignments and State assignments) for the current year.
Please, check that it is working as expected and close this bug.

**Comment by RyanTan8** [comment]
When the "get emails" button is clicked, the event emails page for each event is now blank. I will leave the issue open.

**Comment by wolfe3d** [comment]
Well that was a case issue, but it worked on my test site.  I had references to 'tournamentEvent' instead of 'tournamentevent' in a query in the function getEventEmails.  It should work now.
