### ISSUE TITLE
Student Enrolled and Completed Courses

### ISSUE THREAD

**Issue by ShreyaMeiyappan** [wolfe3d/sodata#41]
The courses of one student are being applied to all the students. When one student's courses are edited, those courses show up for each student.

**Comment by wolfe3d** [comment]
Just confirming the issue:
When you click course completed, the course shows up in the edit screen of other users.  It does not show up in the details of other users unless you edit.

**Comment by wolfe3d** [comment]
I believe that I have corrected this.  Also, I added a way that users can check their own data, so we might know if their mistakes.

**Comment by wolfe3d** [comment]
Shreya check this error.  If it works, close it with a comment.

**Comment by ShreyaMeiyappan** [comment]
The error has been corrected.
