### ISSUE TITLE
"Get Emails" option for event leaders

### ISSUE THREAD

**Issue by ShreyaMeiyappan** [wolfe3d/sodata#42]
The "Get Emails" button for the event leaders are not showing any emails. It just opens a blank page when that button is clicked.

**Comment by wolfe3d** [comment]
There was an error in the mySQL statement.  This has been fixed.  Please test and close this bug.

**Comment by ShreyaMeiyappan** [comment]
The get emails page now shows the list of emails of all of the event leaders.
