### ISSUE TITLE
Courses enrolled/courses completed

### ISSUE THREAD

**Issue by RyanTan8** [wolfe3d/sodata#46]
Courses enrolled and courses completed for each student shows up as an inaccurate result if student info is accessed through the tournament roster, partner listings, or anywhere else besides directly through the teammates tab.

**Comment by wolfe3d** [comment]
I am not sure how to duplicate this bug.  Can you show me at our next meeting an example of this?

**Comment by wolfe3d** [comment]
I think I fixed it by changing row['studentID'] to the variable set earlier $studentID.  Or I made it worse.  Please, check on this.  I cannot duplicate this since I am not logged in as a student.
